import streamlit as st
import requests
import os


# ---------------- API KEY ----------------

API_KEY = os.getenv("OPENROUTER_API_KEY")

if not API_KEY:
    st.error("Missing OPENROUTER_API_KEY. Please set it in your environment variables.")
    st.stop()


# ---------------- PAGE CONFIG ----------------

st.set_page_config(
    page_title="AI Travel Planner",
    layout="wide",
    initial_sidebar_state="expanded"
)


# ---------------- CUSTOM CSS ----------------

st.markdown("""
<style>

.stApp {
    background-image: url("https://images.unsplash.com/photo-1539635278303-d4002c07eae3?fm=jpg&q=60&w=3000&auto=format&fit=crop");
    background-size: cover;
    background-position: center;
    background-attachment: fixed;
}

.stApp::before {
    content: "";
    position: fixed;
    top: 0;
    left: 0;
    width: 100%;
    height: 100%;
    background: rgba(0, 0, 0, 0.45);
    z-index: -1;
}

.main-title {
    font-size: 80px;
    font-weight: bold;
    text-align: center;
    background: linear-gradient(90deg, #ff512f, #dd2476, #1fa2ff);
    background-size: 300% 300%;
    -webkit-background-clip: text;
    -webkit-text-fill-color: transparent;
    animation: gradientMove 6s ease infinite;
    letter-spacing: 3px;
    text-transform: uppercase;
}

@keyframes gradientMove {

    0% {
        background-position: 0% 50%;
    }

    50% {
        background-position: 100% 50%;
    }

    100% {
        background-position: 0% 50%;
    }

}

.card {
    background: white;
    color: #222;
    padding: 25px;
    border-radius: 15px;
    box-shadow: 0px 8px 25px rgba(0,0,0,0.2);
    margin-bottom: 20px;
    line-height: 1.7;
    font-size: 16px;
}

.stButton > button {
    background: linear-gradient(135deg, #ff512f, #dd2476);
    color: white;
    font-weight: bold;
    border-radius: 30px;
    padding: 12px 25px;
    border: none;
    transition: 0.3s;
}

.stButton > button:hover {
    transform: scale(1.05);
    box-shadow: 0px 5px 20px rgba(255, 81, 47, 0.6);
}

section[data-testid="stSidebar"] {
    background: linear-gradient(
        180deg,
        rgba(20,20,20,0.95),
        rgba(40,40,40,0.95)
    );

    backdrop-filter: blur(10px);
    border-right: 1px solid rgba(255,255,255,0.1);
}

section[data-testid="stSidebar"] h2,
section[data-testid="stSidebar"] h1,
section[data-testid="stSidebar"] label {
    color: white !important;
    font-weight: 500;
}

section[data-testid="stSidebar"] .stTextInput input,
section[data-testid="stSidebar"] .stSelectbox div[data-baseweb="select"] {
    background-color: rgba(255,255,255,0.1) !important;
    color: white !important;
    border-radius: 10px !important;
    border: 1px solid rgba(255,255,255,0.2) !important;
}

</style>
""", unsafe_allow_html=True)


# ---------------- TITLE ----------------

st.markdown(
    '<p class="main-title">✈️ AI Travel Planner for Students</p>',
    unsafe_allow_html=True
)

st.write(
    "Discover destinations, costs, and personalized student travel insights using AI."
)


# ---------------- SIDEBAR ----------------

st.sidebar.header("🌍 Trip Details")

destination = st.sidebar.text_input(
    "Destination",
    "Goa"
)

budget = st.sidebar.selectbox(
    "Budget Level",
    ["Low", "Medium", "High"]
)

purpose = st.sidebar.selectbox(
    "Travel Purpose",
    [
        "Study Tour",
        "Adventure Trip",
        "Relaxation",
        "Cultural Exploration",
        "Food Exploration",
        "Photography"
    ]
)


# ---------------- GENERATE BUTTON ----------------

if st.button("🚀 Generate Travel Guide"):

    # ---------------- PROMPT ----------------

    prompt = f"""
You are a professional student travel planner.

Create a clear, practical, human-readable travel guide for:

Destination: {destination}
Budget Level: {budget}
Travel Purpose: {purpose}

IMPORTANT:
The student should be able to read the guide quickly and understand exactly what to do.

STRICT FORMATTING RULES:

1. DO NOT use asterisks (*) anywhere.
2. DO NOT use citations such as [1], [2], [3], [5], etc.
3. DO NOT use markdown tables.
4. DO NOT write long paragraphs.
5. Use clear numbered headings.
6. Use simple bullet points using the "-" symbol only.
7. Keep sentences short and natural.
8. Do not repeat the same information.
9. Give practical information that a student can actually use.
10. Do not mention that the information was generated by AI.
11. Do not add unnecessary explanations.
12. Do not use emojis.
13. Do not use decorative symbols such as *, **, ###, or ##.
14. Keep the formatting consistent throughout the entire response.

Use this exact structure:

1. TRIP OVERVIEW

Give a short 2-3 sentence overview of the destination and why it is suitable for the selected travel purpose.

Then provide:

- Best for:
- Recommended stay:
- Ideal trip duration:
- Main areas to explore:
- Overall experience:

2. TOP PLACES TO VISIT

Give 6-8 important places.

For every place use this format:

Place Name
- Why visit:
- What to see:
- Approximate visit time:
- Cost: Free or approximate cost
- Student tip:

3. DAILY BUDGET

This section is very important.

Give a realistic estimated DAILY budget based on the selected budget level.

Use exactly this format:

Accommodation: ₹X - ₹X
Food: ₹X - ₹X
Local Transportation: ₹X - ₹X
Attractions: ₹X - ₹X
Miscellaneous: ₹X - ₹X

Estimated Daily Total: ₹X - ₹X

Then explain in 2 short points:

- What is included in this budget
- How a student can reduce the cost

Do not add fake precision. Use realistic ranges.

4. TOTAL TRIP BUDGET

Calculate an estimated budget for a 3-day trip.

Show:

Accommodation for 3 days: ₹X - ₹X
Food for 3 days: ₹X - ₹X
Transportation for 3 days: ₹X - ₹X
Attractions: ₹X - ₹X
Miscellaneous: ₹X - ₹X

Estimated Total for 3 Days: ₹X - ₹X

Make sure the total is mathematically consistent with the individual amounts.

5. BEST TIME TO VISIT

Explain:

- Best months:
- Best weather:
- Budget-friendly period:
- Busy period:
- Periods students may want to avoid:

6. FOOD GUIDE

Give practical student-friendly food options.

Breakfast
- 2-3 options
- Approximate cost

Lunch
- 2-3 options
- Approximate cost

Dinner
- 2-3 options
- Approximate cost

Budget food tips:
- 3-4 practical tips

7. TRANSPORTATION GUIDE

Explain:

- Best public transport option
- Approximate daily transportation cost
- How students should pay
- When walking is better
- When public transport is better
- One important transport-saving tip

8. STUDENT-FRIENDLY ACTIVITIES

Give 5 activities.

For each:

Activity
- Approximate cost:
- Time required:
- Why students may enjoy it:

Include a mixture of free and paid activities.

9. SAFETY AND TRAVEL TIPS

Give 6-8 short practical tips covering:

- Personal safety
- Money
- Documents
- Mobile internet
- Weather
- Public transport
- Tourist scams
- Emergency situations

10. QUICK 3-DAY PLAN

Create a simple itinerary:

Day 1
Morning:
Afternoon:
Evening:

Day 2
Morning:
Afternoon:
Evening:

Day 3
Morning:
Afternoon:
Evening:

11. MONEY-SAVING TIPS

Give 6 practical ways a student can reduce travel expenses.

12. FINAL RECOMMENDATION

Give a short 3-4 sentence conclusion explaining whether the destination is suitable for the selected budget and travel purpose.

FINAL CHECK BEFORE ANSWERING:

- No asterisks.
- No [1], [2], [3] citations.
- No tables.
- No long paragraphs.
- Use numbered headings.
- Use "-" for bullets.
- Keep all costs clear.
- Make the daily and 3-day totals mathematically consistent.
- Keep the language simple and human-readable.
"""


    # ---------------- API HEADERS ----------------

    headers = {
        "Authorization": f"Bearer {API_KEY}",
        "Content-Type": "application/json"
    }


    # ---------------- API DATA ----------------

    data = {
        "model": "openrouter/auto",
        "messages": [
            {
                "role": "user",
                "content": prompt
            }
        ],
        "max_tokens": 1000
    }


    # ---------------- API REQUEST ----------------

    with st.spinner("🤖 AI is generating travel guide..."):

        try:

            response = requests.post(
                "https://openrouter.ai/api/v1/chat/completions",
                headers=headers,
                json=data,
                timeout=60
            )


            # ---------------- SUCCESS ----------------

            if response.status_code == 200:

                response_data = response.json()

                # Check that choices exists
                if "choices" in response_data:

                    result = response_data["choices"][0]["message"]["content"]

                    st.success("✅ Travel Guide Ready!")


                    # ---------------- COLUMNS ----------------

                    col1, col2 = st.columns([3, 1])


                    # ---------------- TRAVEL GUIDE ----------------

                    with col1:

                        st.markdown(
                            "### 📍 Destination Travel Guide"
                        )

                        st.markdown(
                            f"""
                            <div class="card">
                            {result}
                            </div>
                            """,
                            unsafe_allow_html=True
                        )


                    # ---------------- TRAVEL TIPS ----------------

                    with col2:

                        st.markdown(
                            "### 💡 Student Travel Tips"
                        )

                        st.markdown(
                            """
                            <div class="card">

                            ✔ Travel in groups to save money<br><br>

                            ✔ Use public transport<br><br>

                            ✔ Book hostels or dorms<br><br>

                            ✔ Eat local food<br><br>

                            ✔ Carry student ID for discounts

                            </div>
                            """,
                            unsafe_allow_html=True
                        )

                else:

                    st.error(
                        "The API response did not contain a travel guide."
                    )

                    st.json(response_data)


            # ---------------- API ERROR ----------------

            else:

                st.error(
                    f"OpenRouter API Error: {response.status_code}"
                )

                try:

                    error_data = response.json()

                    st.json(error_data)

                except Exception:

                    st.write(response.text)


        # ---------------- TIMEOUT ERROR ----------------

        except requests.exceptions.Timeout:

            st.error(
                "The API request timed out. Please try again."
            )


        # ---------------- CONNECTION ERROR ----------------

        except requests.exceptions.RequestException as e:

            st.error(
                f"Connection error: {e}"
            )


        # ---------------- OTHER ERROR ----------------

        except Exception as e:

            st.error(
                f"Something went wrong: {e}"
            )